######################################################################
# Automatically generated by qmake (2.01a) Thu Jul 16 16:57:37 2009
######################################################################

TEMPLATE = app
TARGET = 
PRE_TARGETDEPS += ../lib/libqsilib.a
DEPENDPATH += .
INCLUDEPATH += . ../lib
QMAKE_LIBDIR += ../lib

LIBS += -lqsilib

# Input
SOURCES += main.cpp \
    dialog.cpp

HEADERS += \
    dialog.h

FORMS += \
    dialog.ui
